# Supabase config for local development
[api]
enabled = true
port = 54321
schemas = ["public", "auth", "storage", "graphql_public"]
extra_search_path = ["public", "auth"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[ingest]
enabled = false

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:8080"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_functions]
enabled = true